version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./web:/work
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./web:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    image: neo4j:latest
    build: ./infra/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./database:/data
